# global filter; messages must have at least this severity to pass:
minSeverity: Info

# global file rotation settings:
rotation:
  rpLogLimitBytes: 25000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  #- TraceForwarderBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK
  #- TraceForwarderBK

# file to forward traced objects
#logOutput: "logs/log-pipe-0"

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/node-0.log"
    scFormat: ScJson

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/node-0.log"

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
    'cardano.#messagecounters.aggregation':
      subtrace: NoTrace
    'cardano.#messagecounters.ekgview':
      subtrace: NoTrace
    'cardano.#messagecounters.switchboard':
      subtrace: NoTrace
    'cardano.#messagecounters.katip':
      subtrace: NoTrace
    'cardano.#messagecounters.monitoring':
      subtrace: NoTrace
  mapBackends:
    cardano.node.metrics.ChainDB:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.peers.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 0
Protocol: RealPBFT
GenesisHash: 210e8d1833ab7972e786d5fc330169c2527c8b92ddf22e2528524e789365fdac
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold: 0.7
TurnOnLogging: True
ViewMode: LiveView
TurnOnLogMetrics: False

##### Network Time Parameters #####

ResponseTimeout: 30000000
PollDelay: 1800000000
Servers: [ "0.pool.ntp.org"
         , "2.pool.ntp.org"
         , "3.pool.ntp.org"
         ]

#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0

MemPoolLimitTx: 200
AssetLockedSrcAddress: []

CacheParameter: 500
MessageCacheTimeout: 30

NetworkDiameter: 18
RecoveryHeadersMessage: 2200
StreamWindow: 2048
NonCriticalCQBootstrap: 0.95
NonCriticalCQ: 0.8
CriticalCQBootstrap: 0.8888
CriticalCQ: 0.654321
CriticalForkThreshold: 3
FixedTimeCQ: 3600

SlotLength: 20000
NetworkConnectionTimeout: 15000
HandshakeTimeout: 30000

Enabled: False
Rate: 0
Period: ''
Burst: 0
