# global filter; messages must have at least this severity to pass:
minSeverity: Warning

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the GUI is listening on this port:
# hasGUI: 12787

# if wanted, the EKG interface is listening on this port:
# hasEKG: 12788

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: DevNullSK
    scName: devnull
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - DevNullSK
    - devnull

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapBackends:
    cardano.node.metrics.ChainDB:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.peers.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend

##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 0
Protocol: RealPBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresNoMagic
PBftSignatureThreshold: 0.5
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: False


#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0
