# global filter; messages must have at least this severity to pass:
minSeverity: Warning

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the GUI is listening on this port:
# hasGUI: 12787

# if wanted, the EKG interface is listening on this port:
# hasEKG: 12788

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: DevNullSK
    scName: devnull
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - DevNullSK
    - devnull

# more options which can be passed as key-value pairs:
options:
  mapBackends:
    cardano.node.ChainDB.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision.peers:
      - kind: UserDefinedBK
        name: LiveViewBackend

##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId:
Protocol: RealPBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresNoMagic
PBftSignatureThreshold:
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: False


#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0

#####         Tracing         #####

# MinimalVerbosity: Minimal level of the rendering of captured items
# MaximalVerbosity: Maximal level of the rendering of captured items
# NormalVerbosity: the default level of the rendering of captured items
TracingVerbosity: NormalVerbosity

# Trace BlockFetch client.
TraceBlockFetchClient: False

# Trace BlockFetch decisions made by the BlockFetch client.
TraceBlockFetchDecisions: False

# Trace BlockFetch protocol messages.
TraceBlockFetchProtocol: False

# Serialised Trace BlockFetch protocol messages.
TraceBlockFetchProtocolSerialised: False

# Trace BlockFetch server.
TraceBlockFetchServer: False

# Verbose tracer of ChainDB
TraceChainDb: False

# Trace ChainSync client.
TraceChainSyncClient: False

# Trace ChainSync server (blocks).
TraceChainSyncBlockServer: False

# Trace ChainSync server (headers)
TraceChainSyncHeaderServer: False

# Trace ChainSync protocol messages.
TraceChainSyncProtocol: False

# Trace DNS Resolver messages.
TraceDNSResolver: False

# Trace DNS Subscription messages.
TraceDNSSubscription: False

# Trace error policy resolution.
TraceErrorPolicy: False

# Trace block forging.
TraceForge: False

# Trace IP Subscription messages.
TraceIpSubscription: False

# Trace local ChainSync protocol messages.
TraceLocalChainSyncProtocol: False

# Trace local TxSubmission protocol messages.
TraceLocalTxSubmissionProtocol: False

# Trace local TxSubmission server.
TraceLocalTxSubmissionServer: False

# Trace mempool.
TraceMempool: False

# Trace Mux Events
TraceMux: False

# Trace TxSubmission server (inbound transactions).
TraceTxInbound: False

# Trace TxSubmission client (outbound transactions).
TraceTxOutbound: False

# Trace TxSubmission protocol messages.
TraceTxSubmissionProtocol: False
