on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Cardano Node 
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.node
          tags: emurgornd/cardano-node:latest,emurgornd/cardano-node:${{ github.ref_name }}
      - name: Build and push Cardano Submit API
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.submitapi
          tags: emurgornd/cardano-submit-api:latest,emurgornd/cardano-node:${{ github.ref_name }}
      - name: Build and push Cardano node blockproducer
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.blockproducer
          tags: emurgornd/cardano-node-block-producer:latest,emurgornd/cardano-node-block-producer:${{ github.ref_name }}
      - name: Build and push Cardano node relay
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.relay
          tags: emurgornd/cardano-node-relay:latest,emurgornd/cardano-node-relay:${{ github.ref_name }}
