name: Nightly Trigger

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v3

    - name: Tag
      run: |
        git branch -D nightly || true
        git checkout -b nightly
        git push origin nightly --force

    - name: Invoke workflow
      uses: input-output-hk/workflow-dispatch@v1
      with:
        workflow: .github/workflows/haskell.yml
        ref: nightly
        token: ${{ secrets.MACHINE_TOKEN }}
        inputs: '{ "reason": "nightly", "tests": "all" }'
