name: sync-fork
#env: 
  #UPSTREAM_URL: "http://github.com:input-output-hk/cardano-node.git"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync and merge upstream repository with your current repository
  # You may pin to the exact commit or the version.
  # uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
        # URL of gitHub public upstream repo
            upstream_repo: https://github.com:input-output-hk/cardano-node.git
        # Branch to merge from upstream (defaults to downstream branch)
            upstream_branch: master
        # Branch to merge into downstream
            downstream_branch: master
        # GitHub Bot token
            token: ${{ secrets.WORKFLOW_TOKEN }}
          
